[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn app:app --workers 2 --threads 2 --worker-class gthread --bind 0.0.0.0:$PORT --timeout 120"
